INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('AI-EVAL-HARNESS', 'Assurance', 'Versioned Evaluation Harness', 'agentic-ai', 'expertises/agentic-ai/agentic-ai_avatar_copywriting_devicev_v1.json', 'Versioned cases, thresholds and comparison across changes', 'ADAPT', 'Both', '19,17,22', 'Evaluation harness', 'No performance claim without matched workload', 'Adapt to reproducibility or compute benchmark', 'https://github.com/mckeopharma-web/copywriting/tree/main/expertises/agentic-ai');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('AI-EXEC-LOG', 'Evidence', 'Execution Journal', 'agentic-ai', 'expertises/agentic-ai/', 'Capture objective, sources, tools, cost/latency and review decision', 'ADAPT', 'Compute', '15,4,18', 'Execution provenance', 'Evidence boundary required', 'Adapt to compute execution receipt', 'https://mickael-umt.com/expertises/agentic-ai/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-RESEARCH-OBJECT', 'New / DeSci', 'Research Object Schema', 'NEW', 'NEW', 'Study → protocol → dataset → transform → result → claim → evidence', 'NEW', 'DeSci', '1,15,18', 'Canonical research schema', 'No external effect claim', 'Net-new specialization primitive', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-CLAIM-GRAPH', 'New / DeSci', 'Claim–Evidence Graph', 'NEW', 'NEW', 'Connect scientific claims to results, datasets, code, environment, authors and attestations', 'NEW', 'DeSci', '1,4,18', 'Evidence graph', 'Requires claim-level source closure when public', 'Central differentiator', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-REPRO-CAPSULE', 'New / DeSci', 'Reproducibility Capsule', 'NEW', 'NEW', 'Bind code hash, environment, parameters, dataset version and expected checks', 'NEW', 'DeSci', '15,19,18', 'Reproducibility package', 'Acceptance evidence only unless externally validated', 'Net-new technical deliverable', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-ATTRIBUTION', 'New / DeSci', 'Contributor Attribution Graph', 'NEW', 'NEW', 'Represent contribution, authorship, review and institutional attestation', 'NEW', 'DeSci', '15,18,4', 'Identity / attribution', 'Avoid legal/IP claims without authority', 'Net-new specialization module', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-CONSENT-ACCESS', 'New / DeSci', 'Consent & Access Boundary', 'NEW', 'NEW', 'Keep sensitive data controlled while exposing only allowed evidence/metadata', 'NEW', 'DeSci', '14,16,18', 'Access / privacy architecture', 'EHDS scope only when applicable', 'Critical for decentralized health science', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-STUDY-ATTEST', 'New / DeSci', 'Study Attestation / Verification Receipt', 'NEW', 'NEW', 'Record who verified which property of a study artifact and under what version', 'NEW', 'DeSci', '15,4,19', 'Attestation', 'Does not establish scientific truth by itself', 'Explicit epistemic boundary', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-PROTOCOL-GOV', 'New / DeSci', 'Scientific Protocol Governance', 'NEW', 'NEW', 'Change control for schemas, validation rules, reviewers and dispute handling', 'NEW', 'DeSci', '16,18,22', 'Governance', 'Normative/descriptive only', 'Net-new domain specialization', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DS-REVIEW-GATE', 'New / DeSci', 'Independent Verification Gate', 'NEW', 'NEW', 'Define what another party must be able to verify before a claim is accepted', 'NEW', 'DeSci', '14,19,22', 'Acceptance gate', 'No causality inference', 'Turns evidence architecture into a buyable service', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-WORKLOAD-ENV', 'New / Compute', 'Workload Envelope', 'NEW', 'NEW', 'Bound workload: CPU/GPU/memory/network/data locality/latency/failure tolerance', 'NEW', 'Compute', '14,1,19', 'Workload contract', 'Benchmark must match this envelope', 'Net-new specialization primitive', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-RESOURCE-TOPO', 'New / Compute', 'Resource Topology', 'NEW', 'NEW', 'Map providers, nodes, regions, accelerators, trust and failure domains', 'NEW', 'Compute', '15,18', 'Compute topology', 'Descriptive evidence', 'Net-new technical module', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-EXEC-RECEIPT', 'New / Compute', 'Execution Receipt', 'NEW', 'NEW', 'Capture workload identity, code/model hash, node, environment, inputs, outputs and attestation', 'NEW', 'Compute', '15,4,18', 'Execution provenance', 'No correctness claim beyond verified fields', 'Adapted conceptually from agent execution journal', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-VERIFY-EXEC', 'New / Compute', 'Verifiable Execution Layer', 'NEW', 'NEW', 'Select signatures, remote attestation, TEE, ZK or replication according to property', 'NEW', 'Compute', '1,18,15', 'Verification mechanism', 'Mechanism claim only unless benchmarked', 'Core specialization module', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-TEE-ZK-SELECT', 'New / Compute', 'TEE / ZK / Replication Selector', 'NEW', 'NEW', 'Choose minimum mechanism based on privacy, correctness, latency and cost constraints', 'NEW', 'Compute', '14,18', 'Architecture decision', 'No universal superiority claim', 'Decision asset, not a technology pitch', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-BENCH-HARNESS', 'New / Compute', 'Matched Benchmark Harness', 'NEW', 'NEW', 'Run matched workloads across centralized/decentralized designs with explicit metrics', 'NEW', 'Compute', '6,19,17', 'Benchmark / EUG', 'Metric contract mandatory', 'Supports evidence-grounded buying decision', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-RESILIENCE', 'New / Compute', 'Replication & Fallback Plan', 'NEW', 'NEW', 'Failure handling, retry, replication, provider exit and fallback to centralized path', 'NEW', 'Compute', '16,17,22', 'Resilience', 'Acceptance evidence only', 'Operationally differentiating', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-RESOURCE-MARKET', 'New / Compute', 'Resource Allocation / Market Adapter', 'NEW', 'NEW', 'Abstract scheduling, provider selection, pricing inputs and capacity constraints', 'NEW', 'Compute', '18,15', 'Scheduler / resource market', 'Economics claims require current source + measurement', 'Optional module; not always needed', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-NODE-ATTEST', 'New / Compute', 'Node Identity & Attestation', 'NEW', 'NEW', 'Prove which node/environment executed a workload and under which configuration', 'NEW', 'Compute', '15,4,18', 'Node attestation', 'Attestation scope must be explicit', 'Core verifiable-compute primitive', NULL);
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DC-COST-PERF', 'New / Compute', 'Cost / Performance Envelope', 'NEW', 'NEW', 'Track throughput, latency, availability, cost and verification overhead for a bounded workload', 'NEW', 'Compute', '6,19', 'Metric contract', 'Observed/derived labels mandatory', 'Do not promise cheaper/faster without data', NULL);

-- brick_products
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-TRUST-BOUNDARY', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-TRUST-BOUNDARY', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-VERIFIER-MAP', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-VERIFIER-MAP', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-ATTESTATION', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-ATTESTATION', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-GOVERNANCE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('BLK-GOVERNANCE', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-SOURCE-CONTRACT', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-SOURCE-CONTRACT', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-DATA-MODEL', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-DATA-MODEL', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-TRANSFORM', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-QUALITY-GATE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-QUALITY-GATE', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-LINEAGE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-EVIDENCE-STORE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-EVIDENCE-STORE', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-REPLAY', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DE-REPLAY', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('HT-RISK-BOUNDARY', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('HT-HUMAN-REVIEW', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('HT-LIFECYCLE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('SG-THREAT-MODEL', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('SG-THREAT-MODEL', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('SG-PROMOTION-GATE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('SG-PROMOTION-GATE', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('AI-EVAL-HARNESS', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('AI-EVAL-HARNESS', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('AI-EXEC-LOG', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-RESEARCH-OBJECT', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-CLAIM-GRAPH', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-REPRO-CAPSULE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-ATTRIBUTION', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-CONSENT-ACCESS', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-STUDY-ATTEST', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-PROTOCOL-GOV', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DS-REVIEW-GATE', 1);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-WORKLOAD-ENV', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-RESOURCE-TOPO', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-EXEC-RECEIPT', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-VERIFY-EXEC', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-TEE-ZK-SELECT', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-BENCH-HARNESS', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-RESILIENCE', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-RESOURCE-MARKET', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-NODE-ATTEST', 2);
INSERT INTO brick_products (brick_id, product_id) VALUES ('DC-COST-PERF', 2);

-- brick_sections
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-TRUST-BOUNDARY', 5);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-TRUST-BOUNDARY', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-TRUST-BOUNDARY', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-TRUST-BOUNDARY', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-VERIFIER-MAP', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-VERIFIER-MAP', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-VERIFIER-MAP', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-ATTESTATION', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-ATTESTATION', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-ATTESTATION', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-GOVERNANCE', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-GOVERNANCE', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('BLK-GOVERNANCE', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-SOURCE-CONTRACT', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-SOURCE-CONTRACT', 16);
