INSERT INTO offers (config_id, product_id, tier_id, offer_name, buyer_trigger, outcome, modules_raw, deliverables, typical_format, commercial_model, reusable_core, specific_core, entry_criteria, exit_acceptance, explicit_exclusions, evidence_contract) VALUES ('DC-O3', 2, 3, 'Verifiable Execution PoC', 'The architecture needs measured proof on one workload', 'Run one representative workload and produce independently inspectable execution evidence', 'DC-EXEC-RECEIPT; DC-NODE-ATTEST; DC-BENCH-HARNESS; DE-REPLAY', 'PoC runtime; execution receipts; matched benchmark; verification checks; replay runbook', 'Bounded PoC', 'Milestone', 'New compute modules + reused replay', 'DC-EXEC-RECEIPT; DC-BENCH-HARNESS', 'Representative dataset/workload + comparator', 'Receipt verifies stated fields; benchmark is reproducible', 'No production availability promise', 'Metric contract + observed/derived labels');
INSERT INTO offers (config_id, product_id, tier_id, offer_name, buyer_trigger, outcome, modules_raw, deliverables, typical_format, commercial_model, reusable_core, specific_core, entry_criteria, exit_acceptance, explicit_exclusions, evidence_contract) VALUES ('DC-O4', 2, 4, 'Decentralized Compute Infrastructure Implementation', 'PoC metrics justify production integration', 'Implement distributed execution, verification, monitoring and provider/fallback integration', 'DC-RESOURCE-TOPO; DC-RESOURCE-MARKET; DC-RESILIENCE; SG-PROMOTION-GATE; DE-EVIDENCE-STORE', 'Runtime/integration; scheduler adapters; verification; observability; release gates; handoff', '3–9 months', 'Retainer / milestones', 'Composable platform implementation', 'Provider adapters / performance tuning', 'Accepted PoC + operating ownership', 'Release gate passes on representative workloads', 'No 24/7 ops unless contracted', 'Release evidence + benchmark history');
INSERT INTO offers (config_id, product_id, tier_id, offer_name, buyer_trigger, outcome, modules_raw, deliverables, typical_format, commercial_model, reusable_core, specific_core, entry_criteria, exit_acceptance, explicit_exclusions, evidence_contract) VALUES ('DC-O5', 2, 5, 'Compute Protocol Assurance', 'Existing decentralized compute design needs independent architecture/claim review', 'Check whether trust, execution and performance claims match what the system actually proves', 'SG-THREAT-MODEL; DC-BENCH-HARNESS; DC-NODE-ATTEST; SG-PROMOTION-GATE', 'Claim/evidence ledger; benchmark audit; threat model; failure tests; remediation backlog', 'Project / recurring', 'Retainer / fixed review', 'Reuse assurance + new compute metrics', 'Protocol-specific attack/performance tests', 'Specs/code/benchmark access', 'Claims are classified as supported/bounded/unsupported', 'Not a formal certification', 'Every published numeric claim requires metric contract');

-- offer_bricks
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O1', 'BLK-TRUST-BOUNDARY', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O1', 'DS-RESEARCH-OBJECT', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O1', 'DS-REVIEW-GATE', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O2', 'DS-RESEARCH-OBJECT', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O2', 'DS-CLAIM-GRAPH', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O2', 'DS-CONSENT-ACCESS', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O2', 'SG-THREAT-MODEL', 4);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O2', 'DS-PROTOCOL-GOV', 5);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O3', 'DE-SOURCE-CONTRACT', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O3', 'DE-TRANSFORM', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O3', 'DE-LINEAGE', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O3', 'DS-REPRO-CAPSULE', 4);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O3', 'DS-STUDY-ATTEST', 5);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O4', 'DE-DATA-MODEL', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O4', 'DE-EVIDENCE-STORE', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O4', 'DS-CONSENT-ACCESS', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O4', 'DS-PROTOCOL-GOV', 4);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O4', 'SG-PROMOTION-GATE', 5);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O5', 'SG-THREAT-MODEL', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O5', 'DE-QUALITY-GATE', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O5', 'DS-REVIEW-GATE', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DS-O5', 'DS-PROTOCOL-GOV', 4);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O1', 'DC-WORKLOAD-ENV', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O1', 'BLK-TRUST-BOUNDARY', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O1', 'DC-TEE-ZK-SELECT', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O2', 'DC-RESOURCE-TOPO', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O2', 'DC-VERIFY-EXEC', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O2', 'SG-THREAT-MODEL', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O2', 'DC-RESILIENCE', 4);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O2', 'BLK-GOVERNANCE', 5);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O3', 'DC-EXEC-RECEIPT', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O3', 'DC-NODE-ATTEST', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O3', 'DC-BENCH-HARNESS', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O3', 'DE-REPLAY', 4);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O4', 'DC-RESOURCE-TOPO', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O4', 'DC-RESOURCE-MARKET', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O4', 'DC-RESILIENCE', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O4', 'SG-PROMOTION-GATE', 4);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O4', 'DE-EVIDENCE-STORE', 5);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O5', 'SG-THREAT-MODEL', 1);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O5', 'DC-BENCH-HARNESS', 2);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O5', 'DC-NODE-ATTEST', 3);
INSERT INTO offer_bricks (config_id, brick_id, sequence_no) VALUES ('DC-O5', 'SG-PROMOTION-GATE', 4);

-- evidence_items
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EU-CANON-EHDS-EHR-TESTING-2026', 'Evidence Unit', 'ADMITTED', 'NORMATIVE', 'EHDS-scope EHR testing / technical-documentation context', 'Scope only; not a measured performance effect', '14,19,4,22', 'https://health.ec.europa.eu/ehealth-digital-health-and-care/ehds-action/ehds-platform_en');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EU-HT-EMA-FDA-GOOD-AI-2026', 'Evidence Unit', 'ADMITTED', 'NORMATIVE', 'Risk-based validation, provenance, human-AI assessment, lifecycle monitoring in medicines AI', 'Applies only to relevant AI/medicines context', '4,16,22', 'https://www.ema.europa.eu/en/documents/other/guiding-principles-good-ai-practice-drug-development_en.pdf');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EU-REGCSV-PROOF-PHARMACY-STUDIES-2014-2020', 'Capability Evidence', 'CANONICAL_FACTFULNESS_PASS', 'OBSERVED', 'Scientific/pharmaceutical education context', 'Self-published professional evidence; no certification/outcome inference', '4,5,21', 'https://mickael-umt.com/parcours/pharmacy-studies-strasbourg/');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EU-REGCSV-PROOF-RADIOPHARMACY-2018-2019', 'Capability Evidence', 'CANONICAL_FACTFULNESS_PASS', 'OBSERVED', 'Hospital radiopharmacy quality-control context', 'Supports experience only', '4,5,21', 'https://mickael-umt.com/parcours/strasbourg-radiopharmacy/');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EG-DS-CLAIM-PROVENANCE', 'Evidence Graph', 'PLANNED', 'ARCHITECTURAL', 'Claim → result → dataset → transform → code/environment → contributor/attestation', 'Logical graph is not quantitative evidence by itself', '1,4,18', NULL);
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EUG-DS-RESEARCH-COVERAGE', 'Evidence Graphic', 'BLOCKED_PENDING_SOURCE_CLOSURE', 'PLANNED', 'Candidate visualization of evidence-chain coverage / missing links', 'Do not publish until metric contract + >=5 sourced datapoints', '6,19', NULL);
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EU-CANON-WILEY-DB-VS-DLT-THROUGHPUT-2026', 'Evidence Unit', 'CANONICAL_FACTFULNESS_PASS', 'COMPARATIVE', 'Bounded database vs ledger endpoint throughput under same prototype workload', 'Not universal; not evidence for decentralized compute performance generally', '6,14,4', 'https://onlinelibrary.wiley.com/doi/10.1002/cpe.70897');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('QGEU-CANON-DB-VS-DLT-THROUGHPUT-2026', 'Evidence Graphic', 'FACTFULNESS_PASS', 'COMPARATIVE', '924.79 tx/s database vs 219.23 tx/s ledger in bounded prototype', 'Use as anti-hype boundary: raw throughput and cross-party verification are different criteria', '6', 'https://onlinelibrary.wiley.com/doi/10.1002/cpe.70897');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EU-SG-006', 'Capability Evidence', 'ADMITTED', 'OBSERVED', '26/29 public Lottery dApp commits attributed to RickOwri', 'Contribution proof only; not production security outcome', '4,5', 'https://github.com/RickOwri/Encode-Club-Solidity-Bootcamp-Project-W5-LotteryDapp/commits/main/');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('CAP-RUST', 'Capability Evidence', 'SITE_PROFILE', 'OBSERVED', 'Rust and systems tooling', 'Capability record; no client effect', '5,21', 'https://mickael-umt.com/expertises/rust/');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('CAP-ZK-ZKML', 'Capability Evidence', 'SITE_PROFILE', 'OBSERVED', 'ZK proofs, attestations and private verification', 'To-confirm evidence status; do not overstate', '5,21', 'https://mickael-umt.com/expertises/zk-zkml/');
INSERT INTO evidence_items (evidence_id, evidence_type, status, epistemic_class, supported_use, boundary_non_claim, target_tokens_raw, source_url) VALUES ('EG-DC-EXECUTION-RECEIPT', 'Evidence Graph', 'PLANNED', 'ARCHITECTURAL', 'Workload → code/model → node → environment → input/output → attestation → verifier', 'Graph represents provenance; correctness only for verified fields', '1,4,18', NULL);

-- evidence_products
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EU-CANON-EHDS-EHR-TESTING-2026', 1);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EU-HT-EMA-FDA-GOOD-AI-2026', 1);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EU-REGCSV-PROOF-PHARMACY-STUDIES-2014-2020', 1);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EU-REGCSV-PROOF-RADIOPHARMACY-2018-2019', 1);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EG-DS-CLAIM-PROVENANCE', 1);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EUG-DS-RESEARCH-COVERAGE', 1);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EU-CANON-WILEY-DB-VS-DLT-THROUGHPUT-2026', 2);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('QGEU-CANON-DB-VS-DLT-THROUGHPUT-2026', 2);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EU-SG-006', 2);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('CAP-RUST', 2);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('CAP-ZK-ZKML', 2);
INSERT INTO evidence_products (evidence_id, product_id) VALUES ('EG-DC-EXECUTION-RECEIPT', 2);

-- evidence_sections
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-CANON-EHDS-EHR-TESTING-2026', 5);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-CANON-EHDS-EHR-TESTING-2026', 12);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-CANON-EHDS-EHR-TESTING-2026', 13);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-CANON-EHDS-EHR-TESTING-2026', 20);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-HT-EMA-FDA-GOOD-AI-2026', 13);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-HT-EMA-FDA-GOOD-AI-2026', 14);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-HT-EMA-FDA-GOOD-AI-2026', 20);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-REGCSV-PROOF-PHARMACY-STUDIES-2014-2020', 13);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-REGCSV-PROOF-PHARMACY-STUDIES-2014-2020', 17);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-REGCSV-PROOF-PHARMACY-STUDIES-2014-2020', 18);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-REGCSV-PROOF-RADIOPHARMACY-2018-2019', 13);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-REGCSV-PROOF-RADIOPHARMACY-2018-2019', 17);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-REGCSV-PROOF-RADIOPHARMACY-2018-2019', 18);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EG-DS-CLAIM-PROVENANCE', 6);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EG-DS-CLAIM-PROVENANCE', 13);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EG-DS-CLAIM-PROVENANCE', 16);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EUG-DS-RESEARCH-COVERAGE', 19);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EUG-DS-RESEARCH-COVERAGE', 12);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-CANON-WILEY-DB-VS-DLT-THROUGHPUT-2026', 19);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-CANON-WILEY-DB-VS-DLT-THROUGHPUT-2026', 5);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-CANON-WILEY-DB-VS-DLT-THROUGHPUT-2026', 13);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('QGEU-CANON-DB-VS-DLT-THROUGHPUT-2026', 19);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-SG-006', 13);
INSERT INTO evidence_sections (evidence_id, section_id) VALUES ('EU-SG-006', 17);
