
-- products
INSERT INTO products (product_id, product_code, slug, name, reuse_adapt, new_specific, architecture_thesis, sections_count, reuse_weight_count, new_sections_count, compose_adapt_sections_count) VALUES (1, 'DS', 'decentralized-science', 'Decentralized Science', 'Data Engineering + Blockchain + HealthTech + Security', 'Research object, claim graph, reproducibility, attribution, consent/access, scientific governance', 'Knowledge/evidence is the object: can another party reconstruct and verify the scientific claim?', 23, 6, 11, 12);
INSERT INTO products (product_id, product_code, slug, name, reuse_adapt, new_specific, architecture_thesis, sections_count, reuse_weight_count, new_sections_count, compose_adapt_sections_count) VALUES (2, 'DC', 'decentralized-compute', 'Decentralized Compute', 'Blockchain verifier logic + Security + Replay + Agent execution provenance', 'Workload contract, execution receipt, node attestation, verification selector, matched benchmark', 'Execution is the object: who ran the workload, under what environment, and what can be independently verified?', 23, 4, 15, 8);

-- offer_tiers
INSERT INTO offer_tiers (tier_id, tier_name, stage_order) VALUES (1, 'Diagnostic', 1);
INSERT INTO offer_tiers (tier_id, tier_name, stage_order) VALUES (2, 'Architecture Sprint', 2);
INSERT INTO offer_tiers (tier_id, tier_name, stage_order) VALUES (3, 'PoC', 3);
INSERT INTO offer_tiers (tier_id, tier_name, stage_order) VALUES (4, 'Implementation', 4);
INSERT INTO offer_tiers (tier_id, tier_name, stage_order) VALUES (5, 'Assurance', 5);

-- canonical_sections
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (1, 1, 0, 'hero', 'offer_hero', 'Promise + result + format + decision-maker');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (2, 2, 11, 'triggers', 'purchase_triggers', 'Observable purchase-trigger conditions');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (3, 3, 20, 'consequences', 'problem_consequences', 'Cost of the problem + failed workarounds');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (4, 4, 13, 'audience', 'buyer_fit', 'Buyer identity + operational pressure');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (5, 5, 14, 'qualification', 'qualification_gate', 'Fit / no-fit before selling');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (6, 6, 1, 'proposition', 'value_mechanism', 'Mechanism explaining how the offer works');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (7, 7, 2, 'value', 'value_model', 'Functional / strategic / transaction value');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (8, 8, 10, 'offers', 'buying_configurations', 'How the offer can be bought');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (9, 9, 15, 'deliverables', 'deliverables', 'Concrete transferred artifacts');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (10, 10, 3, 'transformation', 'state_transition', 'Operating-state transition');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (11, 11, 12, 'before-after', 'state_comparison', 'Before/after on matched axes');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (12, 12, 19, 'results', 'acceptance_results', 'Acceptance criteria, not invented ROI');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (13, 13, 4, 'proof', 'execution_proof', 'Capability proof + Evidence Units');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (14, 14, 16, 'scope', 'scope_boundary', 'In/out/dependencies/authority boundaries');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (15, 15, 17, 'process', 'delivery_process', 'Mission delivery flow');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (16, 16, 18, 'modules', 'delivery_modules', 'Composable technical modules');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (17, 17, 5, 'capabilities', 'capability_stack', 'Capabilities activated by the mandate');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (18, 18, 21, 'intersection', 'differentiation', 'Cross-skill specialization');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (19, 19, 6, 'benchmark', 'evidence_benchmark', 'Bounded comparison / evidence graphic');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (20, 20, 22, 'commitments', 'controllable_commitments', 'What is contractually controlled');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (21, 21, 23, 'faq', 'objections_faq', 'Boundary questions and objections');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (22, 22, 7, 'engagement', 'next_step_cta', 'Decision-oriented CTA');
INSERT INTO canonical_sections (section_id, canonical_order, token, section_key, kind, semantic_role) VALUES (23, 23, 8, 'lead-form', 'qualification_form', 'Inputs needed to route the mission');

-- bricks
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('BLK-TRUST-BOUNDARY', 'Mechanism', 'Trust Boundary Map', 'blockchain', 'expertises/blockchain/blockchain_copywriting_devicev_v2.json', 'Identify parties that cannot simply trust one another', 'ADAPT', 'Both', '14,1,16,18', 'Trust model', 'Evidence Unit optional; capability-grounded', 'Start from independently verifiable property, not from blockchain', 'https://github.com/mckeopharma-web/copywriting/tree/main/expertises/blockchain');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('BLK-VERIFIER-MAP', 'Mechanism', 'Property → Verifier → Source', 'blockchain', 'expertises/blockchain/', 'Map what must be independently verified and by whom', 'ADAPT', 'Both', '1,16,18', 'Verification model', 'Claim-level EU for any external assertion', 'Reusable decision spine', 'https://mickael-umt.com/expertises/blockchain/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('BLK-ATTESTATION', 'Technical', 'Attestation / commitment layer', 'blockchain', 'expertises/blockchain/', 'Bind a claim or state to a verifiable commitment', 'ADAPT', 'Both', '15,18,4', 'Signatures / hashes / attestations', 'Capability proof + source-boundary', 'Use only when a trust boundary justifies it', 'https://mickael-umt.com/expertises/blockchain/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('BLK-GOVERNANCE', 'Governance', 'Protocol Change Governance', 'blockchain', 'expertises/blockchain/', 'Define who may change rules, schemas, validators and keys', 'ADAPT', 'Both', '16,18,22', 'Governance / change control', 'Evidence normally descriptive/normative', 'Shared protocol-governance primitive', 'https://mickael-umt.com/expertises/blockchain/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DE-SOURCE-CONTRACT', 'Technical', 'Source Contract', 'data-engineering', 'expertises/data-engineering/data-engineering.copywriting.json', 'Authority, identity, frequency, owner and scope for a source', 'REUSE', 'Both', '15,18', 'Data contract', 'No external claim required', 'Directly reusable', 'https://github.com/mckeopharma-web/copywriting/blob/main/expertises/data-engineering/data-engineering.copywriting.json');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DE-DATA-MODEL', 'Technical', 'Data / Evidence Model', 'data-engineering', 'expertises/data-engineering/data-engineering.copywriting.json', 'Grain, keys, invariants, schemas, bounded contexts', 'ADAPT', 'Both', '1,15,18', 'Data model', 'No external claim required', 'Adapt schema to research objects or compute workloads', 'https://mickael-umt.com/expertises/data-engineering/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DE-TRANSFORM', 'Technical', 'Versioned Transformation', 'data-engineering', 'expertises/data-engineering/data-engineering.copywriting.json', 'Versioned ETL/ELT, checkpoints and failure states', 'REUSE', 'DeSci', '15,18,19', 'Transformation lineage', 'Relevant for reproducibility claims', 'Core of reproducible research pipeline', 'https://mickael-umt.com/expertises/data-engineering/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DE-QUALITY-GATE', 'Assurance', 'Quality Gate', 'data-engineering', 'expertises/data-engineering/data-engineering.copywriting.json', 'Executable invariants, failure states and publication gates', 'REUSE', 'Both', '19,22', 'Quality control', 'Acceptance criteria must be pre-written', 'Reusable acceptance pattern', 'https://mickael-umt.com/expertises/data-engineering/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DE-LINEAGE', 'Evidence', 'Lineage / Provenance Graph', 'data-engineering', 'expertises/data-engineering/data-engineering.copywriting.json', 'Inputs, transformations, versions and owners as a traversable chain', 'REUSE', 'DeSci', '1,15,4,18', 'Evidence graph', 'EU for external provenance claims', 'Primary reusable DeSci asset', 'https://mickael-umt.com/expertises/data-engineering/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DE-EVIDENCE-STORE', 'Evidence', 'Evidence Store / Auditable API', 'data-engineering', 'expertises/data-engineering/data-engineering.copywriting.json', 'Query evidence records and reconstruct decisions', 'ADAPT', 'Both', '15,18,4', 'Evidence API', 'No effect claim without baseline', 'Adapt object schema per domain', 'https://mickael-umt.com/expertises/data-engineering/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('DE-REPLAY', 'Operations', 'Replay / Handoff Runbook', 'data-engineering', 'expertises/data-engineering/data-engineering.copywriting.json', 'Reproduce a run and transfer system ownership', 'REUSE', 'Both', '17,22', 'Replay / runbook', 'Acceptance artifact', 'Directly reusable', 'https://mickael-umt.com/expertises/data-engineering/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('HT-RISK-BOUNDARY', 'Governance', 'Regulated Data / Risk Boundary', 'healthtech-product', 'expertises/healthtech-product/healthtech-product.copywriting.json', 'Separate product mechanism from regulatory authority and sensitive-data boundary', 'ADAPT', 'DeSci', '14,16,22', 'Health-data boundary', 'Use normative EU only within scope', 'Critical for health-science positioning', 'https://github.com/mckeopharma-web/copywriting/blob/main/expertises/healthtech-product/healthtech-product.copywriting.json');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('HT-HUMAN-REVIEW', 'Assurance', 'Human Validation Boundary', 'healthtech-product', 'expertises/healthtech-product/healthtech-product.copywriting.json', 'Explicit human review and responsibility where consequential', 'ADAPT', 'DeSci', '19,22', 'Human-in-the-loop', 'Normative evidence when used as regulatory context', 'Reuse for research review/approval boundaries', 'https://mickael-umt.com/expertises/healthtech-product/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('HT-LIFECYCLE', 'Assurance', 'Lifecycle Monitoring / Re-evaluation', 'healthtech-product', 'expertises/healthtech-product/healthtech-product.copywriting.json', 'Versioning, monitoring and re-evaluation over lifecycle', 'ADAPT', 'DeSci', '17,22', 'Lifecycle control', 'EU-HT-EMA-FDA-GOOD-AI-2026 where applicable', 'Use only when AI/medicine lifecycle applies', 'https://mickael-umt.com/expertises/healthtech-product/');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('SG-THREAT-MODEL', 'Assurance', 'Threat Model', 'ai-security', 'expertises/ai-security/ai-security.copywriting.json', 'Threats, trust assumptions, permissions and attack paths', 'REUSE', 'Both', '14,16,22', 'Threat modelling', 'Capability proof, not outcome proof', 'Directly reusable', 'https://github.com/mckeopharma-web/copywriting/blob/main/expertises/ai-security/ai-security.copywriting.json');
INSERT INTO bricks (brick_id, asset_class, name, source_expertise, source_asset, intended_function, reuse_mode, target_product_raw, canonical_tokens_raw, technical_object, evidence_requirement, composition_note, source_url) VALUES ('SG-PROMOTION-GATE', 'Assurance', 'Promotion / Release Gate', 'ai-security', 'expertises/ai-security/ai-security.copywriting.json', 'Security and quality become conditions of promotion', 'ADAPT', 'Both', '19,22', 'Release gate', 'Acceptance criteria required', 'Maps to protocol admission or workload promotion', 'https://mickael-umt.com/expertises/ai-security/');
