INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-DATA-MODEL', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-DATA-MODEL', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-DATA-MODEL', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-TRANSFORM', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-TRANSFORM', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-TRANSFORM', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-QUALITY-GATE', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-QUALITY-GATE', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-LINEAGE', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-LINEAGE', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-LINEAGE', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-LINEAGE', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-EVIDENCE-STORE', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-EVIDENCE-STORE', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-EVIDENCE-STORE', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-REPLAY', 15);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DE-REPLAY', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('HT-RISK-BOUNDARY', 5);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('HT-RISK-BOUNDARY', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('HT-RISK-BOUNDARY', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('HT-HUMAN-REVIEW', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('HT-HUMAN-REVIEW', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('HT-LIFECYCLE', 15);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('HT-LIFECYCLE', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('SG-THREAT-MODEL', 5);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('SG-THREAT-MODEL', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('SG-THREAT-MODEL', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('SG-PROMOTION-GATE', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('SG-PROMOTION-GATE', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('AI-EVAL-HARNESS', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('AI-EVAL-HARNESS', 15);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('AI-EVAL-HARNESS', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('AI-EXEC-LOG', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('AI-EXEC-LOG', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('AI-EXEC-LOG', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-RESEARCH-OBJECT', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-RESEARCH-OBJECT', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-RESEARCH-OBJECT', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-CLAIM-GRAPH', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-CLAIM-GRAPH', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-CLAIM-GRAPH', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-REPRO-CAPSULE', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-REPRO-CAPSULE', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-REPRO-CAPSULE', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-ATTRIBUTION', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-ATTRIBUTION', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-ATTRIBUTION', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-CONSENT-ACCESS', 5);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-CONSENT-ACCESS', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-CONSENT-ACCESS', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-STUDY-ATTEST', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-STUDY-ATTEST', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-STUDY-ATTEST', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-PROTOCOL-GOV', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-PROTOCOL-GOV', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-PROTOCOL-GOV', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-REVIEW-GATE', 5);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-REVIEW-GATE', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DS-REVIEW-GATE', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-WORKLOAD-ENV', 5);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-WORKLOAD-ENV', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-WORKLOAD-ENV', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-RESOURCE-TOPO', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-RESOURCE-TOPO', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-EXEC-RECEIPT', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-EXEC-RECEIPT', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-EXEC-RECEIPT', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-VERIFY-EXEC', 6);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-VERIFY-EXEC', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-VERIFY-EXEC', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-TEE-ZK-SELECT', 5);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-TEE-ZK-SELECT', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-BENCH-HARNESS', 19);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-BENCH-HARNESS', 12);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-BENCH-HARNESS', 15);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-RESILIENCE', 14);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-RESILIENCE', 15);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-RESILIENCE', 20);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-RESOURCE-MARKET', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-RESOURCE-MARKET', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-NODE-ATTEST', 9);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-NODE-ATTEST', 13);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-NODE-ATTEST', 16);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-COST-PERF', 19);
INSERT INTO brick_sections (brick_id, section_id) VALUES ('DC-COST-PERF', 12);

-- product_sections
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 1, 'DS-RESEARCH-OBJECT', 'COMPOSE', 'Verifiable Research Infrastructure', 'Research workflows whose provenance, computation, attribution and claims can be independently inspected.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 2, 'DS-CLAIM-GRAPH', 'NEW', 'Trigger: disputed provenance or irreproducible workflow', 'A consequential scientific claim cannot be reconstructed end-to-end.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 3, 'DE-LINEAGE', 'ADAPT', 'Consequence: trust collapses into manual reconciliation', 'Teams re-open source, transformation and ownership questions after the fact.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 4, 'HT-RISK-BOUNDARY', 'ADAPT', 'Buyer: research platform / health-data / protocol lead', 'Must coordinate researchers, data owners and reviewers without collapsing authority boundaries.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 5, 'DS-REVIEW-GATE', 'NEW', 'Qualification by independent-verification need', 'If no party needs independent verification, simpler architecture should win.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 6, 'DS-CLAIM-GRAPH', 'NEW', 'Claim → Evidence → Provenance → Computation → Attestation', 'Make the scientific evidence chain queryable and independently inspectable.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 7, 'DS-REPRO-CAPSULE', 'NEW', 'Value = reproducibility + provenance + controlled collaboration', 'Value comes from lower ambiguity, not from decentralization as ideology.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 8, 'DS-REVIEW-GATE', 'COMPOSE', 'Diagnostic → Architecture Sprint → PoC → Implementation → Assurance', 'Buy by uncertainty reduced and artifact produced.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 9, 'DS-REPRO-CAPSULE', 'COMPOSE', 'Research object schema, evidence graph, reproducibility capsule, access boundary, verification receipts', 'Transferred artifacts remain inspectable.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 10, 'DE-LINEAGE', 'ADAPT', 'From fragmented research evidence to reconstructible research claims', 'State transition, not ROI claim.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 11, 'DS-CLAIM-GRAPH', 'NEW', 'Before/after on provenance, reproducibility, attribution and verification', 'Matched axes only.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 12, 'DE-QUALITY-GATE', 'ADAPT', 'Acceptance = traversable claim path + reproducible run + explicit residual uncertainty', 'Pre-write criteria before build.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 13, 'DS-STUDY-ATTEST', 'COMPOSE', 'Use admitted EU + first-party capability proof', 'Proof supports mechanism/capability, never scientific truth or client outcome.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 14, 'DS-CONSENT-ACCESS', 'NEW', 'Sensitive data stays governed; only necessary evidence crosses boundaries', 'No patient-level data on-chain by default.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 15, 'DE-REPLAY', 'ADAPT', 'Map → contract → instrument → reproduce → verify → handoff', 'Each phase leaves an artifact.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 16, 'DS-RESEARCH-OBJECT', 'COMPOSE', 'Composable research protocol modules', 'Activate only modules justified by the trust model.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 17, 'HT-RISK-BOUNDARY', 'COMPOSE', 'Health/pharma + data engineering + verifiable systems + assurance', 'Specialization comes from intersection.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 18, 'DS-PROTOCOL-GOV', 'NEW', 'DeSci ≠ tokenomics; specialization is verifiable research infrastructure', 'Use blockchain/DAO only when the trust boundary justifies it.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 19, 'DS-CLAIM-GRAPH', 'NEW', 'Evidence graphic: claim→artifact→transform→result coverage', 'Do not publish quantitative graph until source/metric contract is closed.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 20, 'DS-PROTOCOL-GOV', 'COMPOSE', 'Control deliverables, boundaries, reversibility and evidence status', 'No clinical, legal, regulatory or ROI guarantee.', 0.5, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 21, 'DS-CONSENT-ACCESS', 'NEW', 'FAQ around privacy, on-chain data, reproducibility, scientific validity and governance', 'Boundary questions first.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 22, 'DS-REVIEW-GATE', 'NEW', 'CTA: bring one disputed/review-critical research claim', 'Decide whether a protocol layer is justified.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
INSERT INTO product_sections (product_id, section_id, primary_brick_id, build_strategy, thesis, composition_note, reuse_weight, evidence_rule) VALUES (1, 23, 'DS-RESEARCH-OBJECT', 'NEW', 'Form asks for study/workflow, data boundary, verifier, claim and decision date', 'Route to diagnostic or no-fit.', 0, 'EU / Evidence Graph only when claim scope and boundary are closed');
